### ISSUE TITLE
cursor is not redrawn/moved on screen when only "C" section present

### ISSUE THREAD

**Issue by MightyPork** [espterm/espterm-firmware#225] opened 2017-09-29 22:35 UTC
try eg moving cursor in a text editor, it gets redrawn only after you stop moving it

i think theres something messed up with the blink timeouts but havent really looked yet, fixing backend atm

**Comment by MightyPork** [comment] 2017-09-29 22:36
with the old format, always the entire screen was redrawn (or at least received), must be related

**Comment by c-probably-archived20260718** [comment] 2017-09-29 22:37
Can't reproduce?

**Comment by MightyPork** [comment] 2017-09-29 22:42
I can 100% with latest `work`

make sure your messages have only C
![screenshot_20170930_004216](https://user-images.githubusercontent.com/2041118/31038639-45b69b84-a578-11e7-9f47-bb0a798456cf.png)

**Comment by MightyPork** [comment] 2017-09-29 22:44
also its more prominent with a non-blinky cursor, blinky cursor tends to recover after about 0.5s

**Comment by c-probably-archived20260718** [comment] 2017-09-29 22:52
oh yeah the cursor update thingy doesn't schedule a draw. Fixed now

**Closed as completed by c-probably-archived20260718** 2017-09-29 22:52 UTC
Labels: bug, front-end

**Comment by MightyPork** [comment] 2017-09-29 22:54
awesome, works fine now!
